# Generated by Django 6.0.6 on 2026-06-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_author_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
