# Generated by Django 6.0.6 on 2026-06-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_date_post_created_at_post_edited_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='edited_at',
            new_name='updated_at',
        ),
    ]
