# Generated by Django 6.0.6 on 2026-07-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_status_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='slug',
        ),
    ]
